server:
  port: 8081
  context-path: /auth


security:
  basic:
    enabled: false


spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: oauth
    password: oauth
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

